#character begining & endings #NPC 1,2,3,4
print ("The Dungeon Master tells the NPC's to go on a journey")
print ("NPC 1, NPC 2, NPC 3, NPC 4 unite together and head out on a journey")
print ("The party encounters a Giant Spider")
print ("The party rolls a 14 barely able to defeat the Giant Spider")
print ("The party continues on their journey")
print ("The party stumbles across a Stone Golem")
print (" The party rolls with an attack roll, the party rolls a 18")
print (" The party takes down the Stone Golem with their fearless attacks")
print (" The party continues it's journey")
print (" The party grows weary luckly they find a Tavern to rest in")
print (" The party recovers hit points, and replenish their resources")
print (" The party continues on their long and dangerous journey")
print ("The party encounters a Cloud Giant")
print ("The party rolls with a attack roll")
print ("The party fails to roll a high roll")
print ("The party is in serious danger and NPC 3 gets struck down")
print ("NPC 3 is critically low, NPC 3 is on one HP")
print ("The party rolls again getting a high enough number to stike down the Cloud Giant Storm King")
print ("The party is weary and need rest")
print ("The party encounter goblins")
print ("The party uses an attack roll")
print ("The party fails to roll a high enough roll")
print ("The party grows to be uneasy")
print ("The Goblin strikes down NPC 3")
print ("NPC 3 has fallen and is now unconscious")
print ("The party rolls an high attack roll")
print ("The party defeats the Goblin and shortly after they found a Tavern")
print ("The party rests in the Tavern and has recovered as well as well as stock on resources")
print (" NPC 3 has made a full recovery and joins back in the battle")
print ("The party continues on the their journey")
print ("The party encounters an Ancient Dragon")
print ("The party shivers in fear but they are filled with determination")
print ("The party rolls an attack roll as well with other die and manage to scrape by")
print ("The party are grows weary but they use their items to enhance their stats")
print ("The party continue on thier journey and come across the ultimate Dragon")
print ("The party encounters a Gold Ancient Dragon")
print ("Your party are stuck with fear wondering if they will become moribund")
print ("The party shakes their heads and with a small glint in their eyes")
print ("They are ready for this monster that they are going to take on")
print (" The party uses their strongest weapons")
print ("unfortunately our story is coming to end")